### ISSUE TITLE
PDF media testing folder

### ISSUE THREAD

**Issue by Dboingue** [jomega-github/kings-gambit-study#1]
[PDF media testing examples](https://github.com/jomega-github/kings-gambit-study/tree/master/pdf)
- I think that the pdf folder should not be there anymore, but in one of my repo where you are also collaborator (I have only 2: one is fork of your, the other the repo extending the lichess PM).
- Since this was the only place at the time, it was fine, but now I think better keep this one for the KG study complements).  What do you think?  
- You can reply, and I will received an email containing it, with a GH generated unique reply email address.  You can also close this issue (and i will know). or both.
- I you agree. i can then link this issue to one of my issues in my repos, and you will know here, that I did and where.  (I will anyway share the proper link with you in lichess, to make sure).

**Comment by Dboingue** [comment]
I forgot to add, that the folder would still be in the commit history of this repository.  I don't know how to get rid of that short of deleting the whole repository, and recreating a new one.

**Comment by jomega-github** [comment]
I still see the pdf folder. In "Code". I'm fine with whatever you want to do. I assume the intent is to capture any chat we do on the KG. Perhaps also to capture the board images? Maybe better to leave the boards in Lichess.

**Comment by Dboingue** [comment]
- [x] - I was waiting for you answer.  i want to take it off.  I will make a repo on the pdf experiments i did.  this was just to test that pdf worked, and while there to show you how the boards behaved. 
- [x] - i was notified only recently (or i missed in my email this morning.  I will take it off.  Also, i am closing this issue. as solved.  when i get to migrate my experiments from mega to a private repo, i will let you know.  very low priority for me.
- [x] - I have the fixes (for each page format, there are small regions (1,2, maybe 3) separated by breakpoints where the boards align with the pieces, but one has to change them each time the source window, is resized

- - [x] - that is why to simplify all my experiment were from full-screen, and margins values solutions i give are for that.  to obtain the correct one for your preferred windows size, one have to use the ones i give and drift from that....


- [ ] - PDF may help maybe for commenting the studies without leaving traces on them, but have pieces where the move list says they should be, would be nice,  and can be done as above.  but i don't intend.  we seem to be ok.  maybe when no time to make a clean reply chapter, a quick pdf annotation may be faster communication.
- [ ] **- Finally, there is one case where it will help: the stockfish evaluation code.  you'll see.**

**Comment by Dboingue** [comment]
- I actually don't know how to remove the folder from GitHub website. I will try with github desktop client.
- It may be that i have to create a branch without it, and then a pull request, because i am not owner.  I should have done this pdf in my fork of this study repo.  
- But first let me try the local client, and then see if I can push the new master version directly.

**Comment by Dboingue** [comment]
- I confirm that using GitHub Desktop to clone this repository as contributor, and deleting the folder on my local machine where the clone repository is stored, via my local OS, makes GH desktop, notice the changes to repo.  
- In order to make the remote (origin) repository (yours on GH), A summary and description is required before committing to the master.  This is a small dialog under the "Changes" column on left hand side of GH desktop, once the repository is selected.  
- the deletion is viewed as all files having been changes, and committing those changes to master, actually allows for a push to origin, of the deletion made via the OS.

I am now really closing this issue.  It can be reviewed and reopened, if similar task is needed. Or I can refer to it, in the minimal GH tip Issues I started in my fork (or one of my related repos).
